#https://raw.githubusercontent.com/Tendry24/library-management/oas-td3-std22076/docs/api.yml
openapi: 3.0.3
info:
  title: Library API
  version: 1.2.0
  description: STD22076
servers:
  - url: https://library.com

tags:
  - name: Books
    description: Operations related to Books
  - name: Authors
    description: Operations related to Books

paths:
  /books:
    get:
      tags:
        - "Books"
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string

        - in: query
          name: startDate
          description: start of intervals
          required: false
          schema:
            type: string
            format: date
        
        - in: query
          name: endDate
          description: end of intervals
          required: false
          schema:
            type: string
            format: date

        - $ref: "#/components/parameters/queryPagination"

        - $ref: "#/components/parameters/pathPagination"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse200'

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse400'
  /books/import:
    post:
      tags:
        - "Books"
      summary: Import books from Excel or JSON
      operationId: importBooks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Book'
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:  
            schema:
              type: string  

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse200'

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse400'
    put:
      tags:
        - "Books"
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse200'

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse400'


  /authors:
    get:
      tags:
        - Authors
      summary: Get all authors
      description: The returned authors are ordered by name.
      operationId: getAuthors
      parameters:
        - in: query
          name: authorName
          description: Filter return Author by given name
          required: false
          schema:
            type: string
        - $ref: "#/components/parameters/queryPagination"
            
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse200'

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse400'


    put: 
      tags:
        - "Authors"
      summary: Create or update a list of Authors
      operationId: CreateOrUpdateAuthor
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/author'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse200'

        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse400'


    delete:
        tags:
        - Authors
        summary: Delete one author
        operationId: deleteAuthorbyId
        parameters:
          - in: query
            name: AuthorId
            required: true
            schema:
              type: integer
            description: ID of the author to delete
        responses:
          '200':
            description: Author deleted successfully

  /books/{bookId}/authors/{authorId}:
    put:
      tags:
        - Books
      summary: Update the author of the book
      parameters:
        - name: bookId
          in: path
          required: true
          description: ID of the book
          schema:
            type: integer
        - name: authorId
          in: path
          required: true
          description: ID of the new author
          schema:
            type: integer
      responses:
        '200':
          description: Opération réussie
        '404':
          description: Livre ou auteur non trouvé

  /authors/import:
    post:
      tags:
        - "Authors"
      summary: Import authors from Excel or JSON
      operationId: importAuthors
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/author'
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
            schema:
              type: string  

      responses:
        '200':
          description: Authors imported successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/author'
  
      
        

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        author:
          type: string
          items:
           $ref: '#/components/schemas/author'
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date

    #TODO1
    author: 
      type: object
      properties:
        id: 
          type: string
          description: id unique
          format: uuid
        name:
          type: string
          description: author's name
        gender:
          type: string
          description: sex of the authors
          enum:
            - M
            - F

    Crupdate:
      allOf:
        - $ref: '#/components/schemas/Book'
        - type: object
          properties:
            Author:
              type: object
              properties:
                ID:
                  type: integer
                authorName:
                  type: string
              nullable: true
          required:
            - ID
            - bookName
            - pageNumbers
            - topic
            - releaseDate
    
    ApiResponse:
      type: object
      properties:
        status:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
        body:
          type: object

    ApiResponse200:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            specificProperty200:
              type: string

    ApiResponse400:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            specificProperty400:
              type: string

    ApiResponse403:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            specificProperty403:
              type: string

    ApiResponse500:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            specificProperty500:
              type: string

  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse200'

    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse400'

    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse403'

    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse500'


      
      


  parameters:
    queryPagination:
      name: Page        
      in: query
      description: Filter return books 
      required: false
      schema:
        type: integer

      
    pathPagination:
      name: pageSize
      in: path
      description: 
      required: true
      schema: 
        type: integer